### ISSUE TITLE
mpv video plane zpos

### ISSUE THREAD

**Issue by T-Firefly** [rockchip-linux/mpv#1]
video plane 默认使用overlay plane , mpv会把zpos 设为0. 
但是如果系统开启了hwCursor之后， 只要有鼠标光标显示，播放界面就是黑的。
若采用swCursor,  osd不会显示，而且即使在窗口最小化下， 视频画面依然会显示。

**Comment by JeffyCN** [comment]
we have not plan to support it, please fire issue upstream:
https://github.com/mpv-player/mpv/issues
